# Generated by Django 4.2.3 on 2023-11-18 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_alter_image_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="description_long",
            new_name="long_description",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="description_short",
            new_name="short_description",
        ),
    ]
